In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[1:8:2] = 10

In [11]:
arr

array([ 0, 10,  2, 10,  4, 10,  6, 10,  8,  9, 10])

In [12]:
arr_2 = arr.copy()

In [13]:
arr_2

array([ 0, 10,  2, 10,  4, 10,  6, 10,  8,  9, 10])

In [14]:
arr_3 = np.array(([1, 2, 3, 4], [3, 4, 5, 6], [7, 8, 9, 4]))

In [15]:
arr_3

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [7, 8, 9, 4]])

In [18]:
arr_3[0][1]

2

In [19]:
arr_3[:2, 1:]

array([[2, 3, 4],
       [4, 5, 6]])

In [34]:
arr_4 = np.zeros((10, 10))

In [41]:
arr_4.shape[0]

10

In [45]:
for i in range(arr_4.shape[0]): arr_4[i] = i

In [46]:
arr_4

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])