# Universal Array Function

In [1]:
import numpy as np

In [4]:
arr = np.array([4, 9, 16, 25, 36, 49, 64])

In [5]:
np.sqrt(arr)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [8]:
np.exp(arr)

array([  5.45981500e+01,   8.10308393e+03,   8.88611052e+06,
         7.20048993e+10,   4.31123155e+15,   1.90734657e+21,
         6.23514908e+27])

In [16]:
A = np.random.randn(10)

In [18]:
A

array([-1.65018754,  0.98030151,  0.45125329, -0.01770699,  0.24746007,
        0.79545501, -0.85178156, -1.16429997, -0.82886205,  1.46490177])

In [13]:
B = np.random.randn(10)

In [17]:
B

array([-1.06149908,  1.02883362,  2.39468428,  0.15551616, -0.46586184,
        0.31888379,  0.40799043,  0.47891627, -0.14815417,  0.11105219])

In [19]:
np.add(A, B)

array([-2.71168662,  2.00913513,  2.84593757,  0.13780917, -0.21840177,
        1.1143388 , -0.44379112, -0.6853837 , -0.97701622,  1.57595396])

In [20]:
np.maximum(A,B)

array([-1.06149908,  1.02883362,  2.39468428,  0.15551616,  0.24746007,
        0.79545501,  0.40799043,  0.47891627, -0.14815417,  1.46490177])