In [17]:
import numpy as np

In [22]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [23]:
np.save('myarr', arr) # save array to the current directory with the 'myarr.npy' name

In [29]:
arr_1 = np.arange(10)
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr_2 = np.load('myarr.npy')

In [31]:
arr_2

array([0, 1, 2, 3, 4])

In [36]:
np.savez('zip_arr', x=arr_1, y=arr_2)

In [38]:
a = np.load('zip_arr.npz')

In [44]:
'x' , a["x"]

('x', array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [45]:
'y', a['y']

('y', array([0, 1, 2, 3, 4]))

In [46]:
arr = np.array(([1, 2, 3], [4, 5, 6]))

In [47]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
np.savetxt('textarr.txt', arr, delimiter=',')

In [58]:
np.loadtxt('textarr.txt', delimiter=',')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])