In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3], dtype=np.float32)
x.itemsize

Out[5]: 4

In [3]:
sinfunc = np.sin(np.array([1, 2, 3], dtype=np.float32))
print(sinfunc)

[0.84147096 0.9092974 0.14112 ]

In [4]:
# Rank two tensor
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x.shape)
print(x)

(2, 3)
[[1 2 3]
 [4 5 6]]

In [5]:
# Slicing in numpy
print(x[:, 0]) # All the rows and 0th column
print(x[:, 1]) # All the rows and 1st column
print(x[0, :]) # All the columns and 0th row
print(x[1, :]) # All the columns and 1st row

[1 4]
[2 5]
[1 2 3]
[4 5 6]

In [6]:
print(x[:, 0:2]) # All the rows and 1st & 2nd columns

[[1 2]
 [4 5]]

In [7]:
# In numpy advance indexing create new copy of an array
m = np.ones((3, 3))
print(m)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

In [8]:
n = m[:, [0, 1, 2, 2]] # Duplicate the last index and add another dimension
print(n.shape)
print(n)

(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

In [9]:
# Here "n" has its own memeory 
# Changing any value of "m" does not affect "n"
m[0, 0] = 99
print(m)
print(n)

[[99. 1. 1.]
 [ 1. 1. 1.]
 [ 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

In [10]:
# Numpy array slicing create views not copy
m = np.array([4,5,6,7])
n = m[:2]
n[0] = 0
print(m)
print(n)

[0 5 6 7]
[0 5]

In [11]:
from numpy.lib.stride_tricks import as_strided

In [12]:
x = np.arange(16, dtype=np.int64)
print(x)
x.strides

[ 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15]
Out[46]: (8,)

In [13]:
y = as_strided(x, (7, 4), (16, 8))
print(y)
print(y.strides)

[[ 0 1 2 3]
 [ 2 3 4 5]
 [ 4 5 6 7]
 [ 6 7 8 9]
 [ 8 9 10 11]
 [10 11 12 13]
 [12 13 14 15]]
(16, 8)

In [14]:
# Numpy matrix
A = np.matrix([[1, 2, 3], [4, 5, 6], [7,8, 9]]) # row = 3 & column = 3
x = np.matrix([[1],[0],[0]]) # row = 3 & column = 1

In [15]:
A @ x # same as A*x

Out[49]: matrix([[1],
 [4],
 [7]])

In [16]:
A = np.ones((3, 3))
x = np.ones((3, 1))
print(np.matrix(A)*x)

[[3.]
 [3.]
 [3.]]

In [17]:
# Broadcasting in numpy
X, Y = np.meshgrid(np.arange(4), np.arange(3))

In [18]:
print(X)
print(Y)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]

In [19]:
x = np.array([0, 1])
y = np.array([0, 1])
print(x)
print(y[:, None]) # convert to 2,1 matrix

[0 1]
[[0]
 [1]]

In [20]:
z = y[:, None]
print(x+z) # broadcast x in axis = 0

[[0 1]
 [1 2]]

In [21]:
z = np.array([0, 1, 2, 3])
z[:, None, None].shape

Out[76]: (4, 1, 1)

In [22]:
# Numpy mashed array
from numpy import ma
x = np.arange(10)
print(x)
y = ma.masked_array(x, x<5) # Creating mask does not copy the array
print(y)
print(y.shape)

[0 1 2 3 4 5 6 7 8 9]
[-- -- -- -- -- 5 6 7 8 9]
(10,)

In [23]:
x[-1] = 99
print(y)

[-- -- -- -- -- 5 6 7 8 99]